---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: relintdockerhubpushbot/cf-deployment-concourse-tasks
    tag: v5.27.0

inputs:
- name: buildpacks-ci
- name: bbl-state

run:
  path: buildpacks-ci/tasks/turn-on-bosh-dns/run.sh

params:
  BBL_STATE_DIR:
