---
platform: linux
image_resource:
  type: docker-image
  source:
    repository: relintdockerhubpushbot/cf-deployment-concourse-tasks
    tag: v5.27.0
inputs:
  - name: buildpacks-ci
  - name: bosh-release
  - name: bbl-state

run:
  path: buildpacks-ci/tasks/upload-bosh-release/run.sh
params:
  BBL_STATE_DIR:
  # ^ relative to bbl-state directory
  # path to bbl-state dir (to run eval "$(bbl print-env)")
  RELEASE:
  # ^ relative to bosh-release input
  # glob to match the release file to upload
